# Preprocessing and filtering TRY

Set path to include RStudio packages

In [23]:
.libPaths(c("/net/home/swolf/R/x86_64-pc-linux-gnu-library/4.4", .libPaths()))

In [24]:
library(data.table)
dtn = 10
setDTthreads(threads = dtn) #defines how many threads data.table is allowed to use

## Taxonomic harmonization with TRY via LCVP

In [55]:
TRY <- fread("../../Data/TRY/TRY6_gapfilled_for_distribution/TRY6_gapfilled_filtered_2.csv")
head(TRY)

  V1 ObservationID Species            Genus   Family      X.X3117.  X.X14.
1 1  1288703       Aa sp              Aa      Orchidaceae  9.450981 26.35165
2 2  3028602       Aa sp              Aa      Orchidaceae  9.527612 26.39279
3 3    20038       Abarema adenophora Abarema Fabaceae    10.809759 22.26771
4 4    20245       Abarema adenophora Abarema Fabaceae    11.419825 24.43851
5 5   251630       Abarema adenophora Abarema Fabaceae    12.559145 24.40643
6 6   748090       Abarema adenophora Abarema Fabaceae    11.983886 25.47936
  X.X50.   X.X146.  X.X3120. ⋯ X.X223.  X.X237.  X.X614.  X.X351.   X.X6.
1 2.795776 21.42593 6.791860 ⋯       NA       NA       NA        NA       NA
2 2.788531 21.47247 6.794565 ⋯       NA       NA       NA        NA       NA
3 2.074678 23.72302 1.749591 ⋯ 26.49628 6.283451 5689.132 0.8451130 2.143766
4 2.158819 22.00696 1.787113 ⋯ 26.58266 6.336021 5313.610 0.8512122 2.027711
5 2.004283 22.03748 1.747104 ⋯ 25.65795 6.040829 4069.435        NA 2.976581
6 2.089632 21.15139 1.989521 ⋯ 27.08000 6.782844       NA        NA       NA
  X.X95.   X.X138.  X.X1080. X.X78.   X.X4.
1       NA       NA NA             NA        NA
2       NA       NA NA             NA        NA
3 60.59445 35.11429 NA       3.426695 0.5816362
4 60.60955 29.54098 NA       3.502891 0.5694862
5       NA 36.52785 NA       3.850584        NA
6 62.18465 36.20889 NA       3.391004        NA

### LDMC error

In [56]:
# replace LDMC with corrected LDMC values
LDMC <- fread("../../Data/gapfilled_filtered_2_new_47.csv")

# filter for columns ObservationID, Species, X.X47. 
LDMC <- LDMC[, c("ObservationID", "Species", "X.X47.")]

head(LDMC)

  ObservationID Species            X.X47.
1 1288703       Aa sp              0.2146660
2 3028602       Aa sp              0.2193361
3   20038       Abarema adenophora 0.4796634
4   20245       Abarema adenophora 0.4726800
5  251630       Abarema adenophora 0.4630560
6  748090       Abarema adenophora 0.4667332

In [57]:
dim(TRY)

[1] 1056032      42

In [58]:
dim(LDMC)

[1] 1055267       3

In [59]:
# merge TRY and LDMC by ObservationID right join add NA'S
merged <- merge(TRY, LDMC, by = "ObservationID", all.x = TRUE)

In [60]:
head(merged)

  ObservationID V1    Species.x             Genus       Family        X.X3117.
1 15473         11926 Acer platanoides      Acer        Sapindaceae   19.199723
2 15474         12228 Acer pseudoplatanus   Acer        Sapindaceae   14.770358
3 15478         48149 Amelanchier lamarckii Amelanchier Rosaceae      11.607862
4 15479         66718 Arbutus unedo         Arbutus     Ericaceae      8.363701
5 15480         86732 Atriplex halimus      Atriplex    Amaranthaceae 10.276161
6 15481         97460 Berberis vulgaris     Berberis    Berberidaceae 15.250665
  X.X14.   X.X50.    X.X146.  X.X3120. ⋯ X.X614.   X.X351.   X.X6.     X.X95.
1 19.62615 0.9138494 24.60834 2.826261 ⋯ 2172.6610 1.0239448 0.4589684       NA
2 21.27231 1.4444071 22.35718 2.997497 ⋯ 2749.9993 1.0039557 0.5077187 90.22336
3 18.26941 1.5882600 27.27290 2.851617 ⋯ 1501.6901 1.3545272 0.9905082 78.55636
4 11.68110 1.4234125 39.42499 2.155804 ⋯ 1360.0421 1.1222717 1.3618612 79.46406
5 28.40755 3.1773270 20.61655 6.440767 ⋯ 4329.3296 0.8741936 1.0027438 88.81030
6 19.73846 1.2609245 21.11955 3.379788 ⋯  905.0342 1.7655882 0.2405496 73.04419
  X.X138.     X.X1080.  X.X78.     X.X4.     Species.y             X.X47..y
1    2.711863 2366.6744  0.8304251 0.5770587 Acer platanoides      0.3721193
2 1419.320539 3155.9017 -0.6870736 0.5859499 Acer pseudoplatanus   0.3486814
3    9.673125 1116.4587 -2.9897895 0.7113116 Amelanchier lamarckii 0.3566795
4  103.033294  614.2494 -5.0258203 0.7814238 Arbutus unedo         0.3928403
5  919.943290  485.1550  1.7171031 0.6085734 Atriplex halimus      0.1787561
6 3134.953964 3229.6911 -3.8981231 0.6411618 Berberis vulgaris     0.3363186

In [61]:
# stats on X.X47..y
summary(merged$X.X47..y)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.050   0.232   0.321   0.316   0.397   0.750  128752

In [62]:
# stats on X.X48..y
summary(merged$X.X47..x)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.080   0.101   0.108   0.107   0.113   0.141  127665

In [63]:
dim(merged)

[1] 1056032      44

In [64]:
# rename X.X47..y to X.X47.
setnames(merged, "X.X47..y", "X.X47.")
setnames(merged, "Species.x", "Species")

# delete X.X47..x
merged[, X.X47..x := NULL]
merged[, Species.y := NULL]

In [65]:
TRY <- merged

In [66]:
#Number of unique species in gap-filled dataset:

length(unique(TRY[["Species"]]))

[1] 74245

### Load harmonization results

--\> recieved from David Schellenberger Costa, based on 

TRY names checked against Leipzig Catalogue of Vascular Plants (LCVP), so they include the GBIF id's and the WCVP id.

In [67]:
# load the taxonomic harmonization file from David's script (TRY_GloNAF_GBIF_matching_Sophie_2024-10-01.csv)

tax_harmony <- fread("../../Results/Data/TRY_GloNAF_GBIF_matching_Sophie_2024-10-01")
head(tax_harmony)

  TRY_name                  GloNAF_name nameIn                    authorsIn
1 ACAENA NOVAE-ZELANDIAE                Acaena novae-zelandiae    NA
2 ADIANTUM CAPILLUS-VENERIS             Adiantum capillus-veneris NA
3 ALISMA PLANTAGO-AQUATICA              Alisma plantago-aquatica  NA
4 APERA SPICA-VENTI                     Apera spica-venti         NA
5 ARCTOSTAPHYLOS UVA-URSI               Arctostaphylos uva-ursi   NA
6 ATROPA BELLA-DONNA                    Atropa bella-donna        NA
  genus          species1          GBIFKeyGBIF searchTypeGBIF synonymGBIF
1 Acaena         novae-zelandiae   5370755     1              FALSE
2 Adiantum       capillus-veneris  2651816     1              FALSE
3 Alisma         plantago-aquatica 2865100     1              FALSE
4 Apera          spica-venti       5289642     1              FALSE
5 Arctostaphylos uva-ursi          2882580     1              FALSE
6 Atropa         bella-donna       3802655     1              FALSE
  matchNameGBIF             ⋯ infraSpecificEpithetGBIF bracketAuthorshipGBIF
1 Acaena novae-zelandiae    ⋯
2 Adiantum capillus-veneris ⋯
3 Alisma plantago-aquatica  ⋯
4 Apera spica-venti         ⋯                          L.
5 Arctostaphylos uva-ursi   ⋯                          L.
6 Atropa bella-donna        ⋯
  kingdomGBIF timeGBIF scientificNameGBIF
1 NA          0.43     Acaena novae-zelandiae Kirk
2 NA          0.44     Adiantum capillus-veneris L.
3 NA          0.42     Alisma plantago-aquatica L.
4 NA          0.42     Apera spica-venti (L.) P.Beauv.
5 NA          0.42     Arctostaphylos uva-ursi (L.) Spreng.
6 NA          0.43     Atropa belladonna L.
  canonicalNameGBIF         genusOrAboveGBIF specificEpithetGBIF rankMarkerGBIF
1 Acaena novae-zelandiae    Acaena           novae-zelandiae     sp.
2 Adiantum capillus-veneris Adiantum         capillus-veneris    sp.
3 Alisma plantago-aquatica  Alisma           plantago-aquatica   sp.
4 Apera spica-venti         Apera            spica-venti         sp.
5 Arctostaphylos uva-ursi   Arctostaphylos   uva-ursi            sp.
6 Atropa belladonna         Atropa           belladonna          sp.
  authorshipGBIF
1 Kirk
2 L.
3 L.
4 P.Beauv.
5 Spreng.
6 L.

In [68]:
# Remove duplicate rows and entries with missing or empty TRY names
tax_harmony <- unique(tax_harmony[TRY_name != ""])

# Retain only the TRY species name and corresponding GBIF key
tax_harmony <- unique(tax_harmony[, c("TRY_name", "GBIFKeyGBIF")])

head(tax_harmony)

  TRY_name                  GBIFKeyGBIF
1 ACAENA NOVAE-ZELANDIAE    5370755
2 ADIANTUM CAPILLUS-VENERIS 2651816
3 ALISMA PLANTAGO-AQUATICA  2865100
4 APERA SPICA-VENTI         5289642
5 ARCTOSTAPHYLOS UVA-URSI   2882580
6 ATROPA BELLA-DONNA        3802655

In [69]:
setnames(tax_harmony, "TRY_name", "Species")

In [70]:
# merge GBIF ID's with TRY
TRY <- merge(TRY, tax_harmony,  by = "Species")
setnames(TRY, "GBIFKeyGBIF", "speciesKey")
head(TRY)

  Species                ObservationID V1   Genus  Family   X.X3117. X.X14.
1 ACAENA NOVAE-ZELANDIAE   37850       8362 Acaena Rosaceae 12.67396 21.37736
2 ACAENA NOVAE-ZELANDIAE   67469       8363 Acaena Rosaceae 12.74442 21.40897
3 ACAENA NOVAE-ZELANDIAE  993211       8364 Acaena Rosaceae 12.88342 21.41249
4 ACAENA NOVAE-ZELANDIAE 1302065       8365 Acaena Rosaceae 12.45588 21.22520
5 ACAENA NOVAE-ZELANDIAE 1354663       8366 Acaena Rosaceae 12.82609 21.05684
6 ACAENA NOVAE-ZELANDIAE 1454164       8367 Acaena Rosaceae 12.58036 21.66270
  X.X50.   X.X146.  X.X3120. ⋯ X.X614.  X.X351.  X.X6.      X.X95.   X.X138.
1 1.752519 20.87031 2.209944 ⋯ 2181.279 1.262439 0.07229195 99.84698 NA
2 1.742883 20.92950 2.273707 ⋯ 2345.986 1.256448 0.07051923 98.52456 NA
3 1.732978 21.02178 2.224450 ⋯ 2264.623 1.251842 0.07154634 98.53554 NA
4 1.768507 21.10937 2.234596 ⋯ 2253.445 1.233911 0.07426102 98.84040 NA
5 1.714608 21.29464 2.239305 ⋯ 2305.833 1.258646 0.07099218 99.18508 NA
6 1.781007 20.72742 2.188924 ⋯ 2222.927 1.247776 0.07882254 98.50396 NA
  X.X1080. X.X78. X.X4.     X.X47.    speciesKey
1       NA NA     0.4412046 0.3376389 5370755
2 5522.859 NA     0.4401498 0.3451679 5370755
3       NA NA     0.4407337 0.3421999 5370755
4       NA NA     0.4435781 0.3370715 5370755
5       NA NA     0.4523186 0.3345291 5370755
6       NA NA     0.4471760 0.3455498 5370755

## Calculate species trait means

In [71]:
library(dplyr)

# Group the data by Species and calculate the mean for each trait
TRY_species_means <- TRY %>%
  group_by(speciesKey) %>%  # Use Species Key !!
  summarise(across(starts_with("X"), ~ mean(.x, na.rm = TRUE))) # Use `across()` to get the mean of all trait columns

In [72]:
head(TRY_species_means)

  speciesKey X.X3117.  X.X14.   X.X50.   X.X146.  X.X3120. X.X224.  X.X297.
1    2393          NaN      NaN      NaN      NaN      NaN      NaN       NaN
2    6655     9.321433      NaN 2.149281      NaN 2.784474      NaN       NaN
3    6657    17.527908 25.95187 1.423995 18.99770 2.455510      NaN 13.749035
4    6752          NaN      NaN      NaN      NaN      NaN      NaN       NaN
5    7717    12.245032 21.21620 2.022381 22.12193      NaN 3.672329 14.885849
6 1010512     9.473567 17.16218 2.126191 24.66683 2.384060 1.338781  7.013938
  X.X21.      X.X13.   ⋯ X.X237.  X.X614.  X.X351.   X.X6.    X.X95.
1         NaN      NaN ⋯      NaN      NaN       NaN      NaN      NaN
2 0.007640780      NaN ⋯ 8.897962      NaN 0.7183379      NaN      NaN
3 0.004666096      NaN ⋯      NaN 2390.416       NaN      NaN      NaN
4         NaN      NaN ⋯      NaN      NaN       NaN      NaN      NaN
5 0.040939324      NaN ⋯ 4.331903      NaN 1.5688087 1.166276 93.53081
6 0.134267482 414.5069 ⋯ 1.665713 2630.476 1.0977119 1.895727 87.15040
  X.X138.   X.X1080.  X.X78.   X.X4.     X.X47.
1       NaN       NaN      NaN       NaN       NaN
2  541.0121 2647.8870      NaN 0.7780896 0.4039974
3 2327.8265 3590.6496      NaN 0.6077446 0.3734142
4       NaN       NaN      NaN       NaN       NaN
5       NaN 6500.2818 4.228426 0.5170459 0.2973159
6  189.7187  637.9941 1.564110 0.4896163 0.4136595

In [73]:
total_missingness <- sum(is.na(TRY_species_means)) / prod(dim(TRY_species_means))
print(total_missingness)

[1] 0.2462466

In [74]:
# Calculate missingness per column
column_missingness <- round(colSums(is.na(TRY_species_means)) / nrow(TRY_species_means), 2)
print(column_missingness)
mean(column_missingness)

speciesKey   X.X3117.     X.X14.     X.X50.    X.X146.   X.X3120.    X.X224.
      0.00       0.34       0.27       0.34       0.28       0.30       0.21
   X.X297.     X.X21.     X.X13.     X.X15.   X.X3114.   X.X3113.   X.X3112.
      0.24       0.22       0.26       0.27       0.29       0.29       0.31
   X.X169.   X.X3106.    X.X144.     X.X27.     X.X26.     X.X55.     X.X46.
      0.25       0.23       0.25       0.18       0.11       0.31       0.27
   X.X281.    X.X282.    X.X289.    X.X163.    X.X145.   X.X3107.    X.X223.
      0.24       0.25       0.26       0.31       0.27       0.23       0.20
   X.X237.    X.X614.    X.X351.      X.X6.     X.X95.    X.X138.   X.X1080.
      0.21       0.23       0.24       0.26       0.22       0.26       0.23
    X.X78.      X.X4.     X.X47.
      0.24       0.20       0.29

[1] 0.2463158

In [75]:
fwrite(TRY_species_means, "../../Results/Data/01_try6_gapfilled_species_means.csv", row.names = F, quote = T)

In [30]:
TRY_species_means <- fread("../../Results/Data/01_try6_gapfilled_species_means.csv")
head(TRY_species_means)

  speciesKey X.X3117.  X.X14.   X.X50.   X.X146.  X.X3120. X.X224.  X.X297.
1    2393           NA       NA       NA       NA       NA       NA        NA
2    6655     9.321433       NA 2.149281       NA 2.784474       NA        NA
3    6657    17.527908 25.95187 1.423995 18.99770 2.455510       NA 13.749035
4    6752           NA       NA       NA       NA       NA       NA        NA
5    7717    12.245032 21.21620 2.022381 22.12193       NA 3.672329 14.885849
6 1010512     9.473567 17.16218 2.126191 24.66683 2.384060 1.338781  7.013938
  X.X21.      X.X13.   ⋯ X.X223.  X.X237.  X.X614.  X.X351.   X.X6.    X.X95.
1          NA       NA ⋯       NA       NA       NA        NA       NA       NA
2 0.007640780       NA ⋯ 32.96780 8.897962       NA 0.7183379       NA       NA
3 0.004666096       NA ⋯ 31.58875       NA 2390.416        NA       NA       NA
4          NA       NA ⋯       NA       NA       NA        NA       NA       NA
5 0.040939324       NA ⋯       NA 4.331903       NA 1.5688087 1.166276 93.53081
6 0.134267482 414.5069 ⋯ 27.28636 1.665713 2630.476 1.0977119 1.895727 87.15040
  X.X138.   X.X1080.  X.X78.   X.X4.
1        NA        NA       NA        NA
2  541.0121 2647.8870       NA 0.7780896
3 2327.8265 3590.6496       NA 0.6077446
4        NA        NA       NA        NA
5        NA 6500.2818 4.228426 0.5170459
6  189.7187  637.9941 1.564110 0.4896163

In [ ]:
total_missingness <- sum(is.na(TRY_species_means)) / prod(dim(TRY_species_means))
print(total_missingness)

[1] 0.2460851

# Filter GBIF for species in TRY6

In [44]:
if (!exists("gbif_dt")){
  #gbif_dt <- fread("../Results/Data/01_prep_gbif-coord-clean.csv", na.strings = "") #nrow = 1000
  gbif_dt <- fread("../Results/Data/01_prep_gbif-coord-clean_sc.csv", na.strings = "") }#nrow = 1000

In [45]:
gbif_dt <- gbif_dt[,c("gbifID", "speciesKey", "decimalLatitude", "decimalLongitude")]
head(gbif_dt)

  gbifID     speciesKey decimalLatitude decimalLongitude
1 3352641301 3103791    56.14011        -3.369429
2 4951294464 8059811    54.97456        -1.634406
3 4866764380 2878688    54.99222        -1.540470
4 3098399480 5361779    52.75213         1.511204
5 5158856302 8377689    51.60241        -1.122803
6 3098399483 5371825    51.10395        -1.993522

In [46]:
gbif_dt_filtered <- semi_join(gbif_dt, TRY_species_means, by = "speciesKey")
head(gbif_dt_filtered)

  gbifID     speciesKey decimalLatitude decimalLongitude
1 3352641301 3103791    56.14011        -3.369429
2 4951294464 8059811    54.97456        -1.634406
3 4866764380 2878688    54.99222        -1.540470
4 3098399480 5361779    52.75213         1.511204
5 5158856302 8377689    51.60241        -1.122803
6 3098399483 5371825    51.10395        -1.993522

In [ ]:
# after filtering
# number of occurences with at least one trait value in TRY6 gap-filled dataset:

dim(gbif_dt_filtered)[1]

[1] 64141358

In [47]:
# Percentage of GBIF observations matched with TRY:
#dim(gbif_dt_filtered)[1]/dim(gbif_dt)[1]*100

#Percentage CS only matched to TRY:
dim(gbif_dt_filtered)[1]/dim(gbif_dt)[1]*100

[1] 92.94343

In [48]:
#Percentage of species from GBIF matched:
#length(unique(gbif_dt_filtered[["speciesKey"]]))/length(unique(gbif_dt[["speciesKey"]]))*100

#Percentage species matched CS-TRY:
length(unique(gbif_dt_filtered[["speciesKey"]]))/length(unique(gbif_dt[["speciesKey"]]))*100

[1] 37.24989

In [49]:
#Percentage of species from TRY matched to GBIF:
#length(unique(gbif_dt_filtered[["speciesKey"]]))/length(unique(TRY_species_means[["speciesKey"]]))*100

#Percentage of species from TRY matched to CS only:
length(unique(gbif_dt_filtered[["speciesKey"]]))/length(unique(TRY_species_means[["speciesKey"]]))*100

[1] 59.5852

In [ ]:
fwrite(gbif_dt_filtered, "/net/scratch/swolf/GBIF/gbif_try_filtered_cs.csv", row.names = F, quote = T)