## Longevity Data

In [29]:
# read ~/Func_Neo_Phytes/Data/TRY/47270_17022026112317/47270.txt as pd
import pandas as pd

df = pd.read_csv("~/Func_Neo_Phytes/Data/TRY/47270_17022026112317/47270.txt", sep="\t", encoding='latin1', low_memory=False)
df.head()

,LastName,FirstName,DatasetID,Dataset,SpeciesName,AccSpeciesID,AccSpeciesName,ObservationID,ObsDataID,TraitID,...,Replicates,StdValue,UnitName,RelUncertaintyPercent,OrigObsDataID,ErrorRisk,Reference,Comment,StdValueStr,Unnamed: 28
0,Cornelissen,Johannes,1,Abisko & Sheffield Database,Achillea millefolium,909,Achillea millefolium,15141,432393,59.0,...,NaN,NaN,year,NaN,NaN,NaN,"Cornelissen, J. H. C., H. M. Quested, D. Gwynn...","P=Perennial, A=Annual",NaN,NaN
1,Cornelissen,Johannes,1,Abisko & Sheffield Database,Angelica sylvestris,3738,Angelica sylvestris,15144,432400,59.0,...,NaN,NaN,year,NaN,NaN,NaN,"Cornelissen, J. H. C., H. M. Quested, D. Gwynn...","P=Perennial, A=Annual",NaN,NaN
2,Cornelissen,Johannes,1,Abisko & Sheffield Database,Anthriscus sylvsteris,4045,Anthriscus sylvestris,15145,432403,59.0,...,NaN,NaN,year,NaN,NaN,NaN,"Cornelissen, J. H. C., H. M. Quested, D. Gwynn...","P=Perennial, A=Annual",NaN,NaN
3,Cornelissen,Johannes,1,Abisko & Sheffield Database,Bartsia alpina,6930,Bartsia alpina,15149,432411,59.0,...,NaN,NaN,year,NaN,NaN,NaN,"Cornelissen, J. H. C., H. M. Quested, D. Gwynn...","P=Perennial, A=Annual",NaN,NaN
4,Cornelissen,Johannes,1,Abisko & Sheffield Database,Caltha palustris,9768,Caltha palustris,15153,432422,59.0,...,NaN,NaN,year,NaN,NaN,NaN,"Cornelissen, J. H. C., H. M. Quested, D. Gwynn...","P=Perennial, A=Annual",NaN,NaN

In [30]:
# number of unique values in "AccSpeciesName"
df['AccSpeciesName'].nunique()

24672

In [31]:
# column names
df.columns

Index(['LastName', 'FirstName', 'DatasetID', 'Dataset', 'SpeciesName',
       'AccSpeciesID', 'AccSpeciesName', 'ObservationID', 'ObsDataID',
       'TraitID', 'TraitName', 'DataID', 'DataName', 'OriglName',
       'OrigValueStr', 'OrigUnitStr', 'ValueKindName', 'OrigUncertaintyStr',
       'UncertaintyName', 'Replicates', 'StdValue', 'UnitName',
       'RelUncertaintyPercent', 'OrigObsDataID', 'ErrorRisk', 'Reference',
       'Comment', 'StdValueStr', 'Unnamed: 28'],
      dtype='object')

In [32]:
# filter for columns 'StdValueStr', 'OrigValueStr', 'OrigUnitStr', 'TraitID', 'AccSpeciesID', 'AccSpeciesName'
df_longevity = df[['StdValueStr', 'OrigValueStr', 'OrigUnitStr', 'TraitID', 'AccSpeciesID', 'AccSpeciesName', 'Comment']]
df_longevity.head(100)

,StdValueStr,OrigValueStr,OrigUnitStr,TraitID,AccSpeciesID,AccSpeciesName,Comment
0,NaN,perennial,NN,59.0,909,Achillea millefolium,"P=Perennial, A=Annual"
1,NaN,perennial,NN,59.0,3738,Angelica sylvestris,"P=Perennial, A=Annual"
2,NaN,perennial,NN,59.0,4045,Anthriscus sylvestris,"P=Perennial, A=Annual"
3,NaN,perennial,NN,59.0,6930,Bartsia alpina,"P=Perennial, A=Annual"
4,NaN,perennial,NN,59.0,9768,Caltha palustris,"P=Perennial, A=Annual"
...,...,...,...,...,...,...,...
95,NaN,100-160,m,NaN,56268,Veronica persica,NaN
96,NaN,annual,NN,59.0,6328,Avena barbata,Lifespan: annual ; perennial
97,NaN,43.85,degree,NaN,6328,Avena barbata,NaN
98,NaN,3.93,degree,NaN,6328,Avena barbata,NaN
99,NaN,100-160,m,NaN,6328,Avena barbata,NaN

In [34]:
# filter for "annual" or "perennial" in "OrigValueStr"
df_longevity_cat = df_longevity[df_longevity['OrigValueStr'].str.strip().str.casefold().isin(['annual', 'perennial'])]
df_longevity_cat.head()

,StdValueStr,OrigValueStr,OrigUnitStr,TraitID,AccSpeciesID,AccSpeciesName,Comment
0,NaN,perennial,NN,59.0,909,Achillea millefolium,"P=Perennial, A=Annual"
1,NaN,perennial,NN,59.0,3738,Angelica sylvestris,"P=Perennial, A=Annual"
2,NaN,perennial,NN,59.0,4045,Anthriscus sylvestris,"P=Perennial, A=Annual"
3,NaN,perennial,NN,59.0,6930,Bartsia alpina,"P=Perennial, A=Annual"
4,NaN,perennial,NN,59.0,9768,Caltha palustris,"P=Perennial, A=Annual"

In [35]:
df_longevity_cat.shape

(38760, 7)

In [36]:
# keep only columns "AccSpeciesName" and "OrigValueStr"
df_longevity_cat = df_longevity_cat[['AccSpeciesName', 'OrigValueStr']]
df_longevity_cat.head()

          AccSpeciesName OrigValueStr
0   Achillea millefolium    perennial
1    Angelica sylvestris    perennial
2  Anthriscus sylvestris    perennial
3         Bartsia alpina    perennial
4       Caltha palustris    perennial

In [37]:
# filter for unique rows
df_longevity_cat = df_longevity_cat.drop_duplicates()
df_longevity_cat.head()

          AccSpeciesName OrigValueStr
0   Achillea millefolium    perennial
1    Angelica sylvestris    perennial
2  Anthriscus sylvestris    perennial
3         Bartsia alpina    perennial
4       Caltha palustris    perennial

In [38]:
# get dimensions of df_longevity_cat
df_longevity_cat.shape

(23978, 2)

In [39]:
# number of unique values for "AccSpeciesName"
df_longevity_cat['AccSpeciesName'].nunique()

21254

In [40]:
# save df_longevity_cat as csv
df_longevity_cat.to_csv("~/Func_Neo_Phytes/Data/TRY/47270_17022026112317/47270_longevity_categorical.csv", index=False)

In [10]:
# unique values for "OrigValueStr"
df_longevity['OrigValueStr'].unique()

# count unique values for "OrigValueStr"
#df_longevity['OrigValueStr'].nunique()

array(['perennial', 'annual', '43.85', ..., '1.0094', '1.0321', '1.0201'],
      dtype=object)

In [13]:
# Filter for values in "OrigValueStr" that are numeric
df_longevity_numeric = df_longevity[pd.notna(df_longevity['OrigValueStr']) & df_longevity['OrigValueStr'].str.isnumeric()]
df_longevity_numeric.head()

,StdValueStr,OrigValueStr,OrigUnitStr,TraitID,AccSpeciesID,AccSpeciesName
151,NaN,6,NaN,NaN,839,Acer monspessulanum
154,NaN,10,NaN,NaN,839,Acer monspessulanum
161,NaN,6,NaN,NaN,839,Acer monspessulanum
167,NaN,6,NaN,NaN,909,Achillea millefolium
170,NaN,10,NaN,NaN,909,Achillea millefolium

In [16]:
# get info on "OrigValueStr" column
df_longevity_numeric['OrigValueStr'].describe()

count    74220.000000
mean      2049.219051
std       7037.661981
min          0.000000
25%          8.000000
50%         77.000000
75%        781.000000
max      61197.000000
Name: OrigValueStr, dtype: float64